// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTest_TESS.Models;

namespace WebTest_TESS.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20210209223533_Crudoperation")]
    partial class Crudoperation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebTest_TESS.Models.Tasks", b =>
                {
                    b.Property<int>("pk_Task")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("complete_Task")
                        .HasColumnType("bit");

                    b.Property<DateTime>("date_Task")
                        .HasColumnType("datetime2");

                    b.Property<string>("name_Task")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pk_Task");

                    b.ToTable("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
